import { PaymentMode, CreditCardType } from "../constants";

export interface IPaymentResponse {
    VoucherNo: string,
    PaymentId: number,
    ToltalAmountPaid: number,
    PaymentMode: PaymentMode,
    TransactionDate: Date,
    BankAccountNumber: string,
    BankName: string,
    CardType: CreditCardType,
    ChequeNumber: string,
    CCSuffix4: string,
    ExpDate: string,
    CustomerId: number,
    NameOnCard: string,
    BankAccountName: string,
    CardNumber: string,
    RebillType: string,
    RebillAmount: number,
    ThresholdAmount: number,
    IsManualHold: boolean,
    MoneyOrderNumber: string,
    EmailAddress: string,
    TripIds: string,
    AdjustmentId: number,
    BalanceType: string,
    FeeAmounts: number,
    isRevenue: boolean,
    RespMsg: string,
    PayPalErrorCode: string,
    ErrorCode: string,
    StatusCode: string,
    PromoId: number,
    PromoCode: string,
    CreditCardServiceTax: number,
    TotalShippingCharge: number,
    EMIAmount: number,
    PaymentFor: string,
    SuccessMsg: string,
    ErrorMsg: string,
    PaymentDate: Date,
    Banksuffix: number,
    IsAnonymousTransfer: boolean,
    UpdatedUser: string,
    ViolationProcess: string,
    FeatureName: string
}
