
export interface IaddCashDetailsResponse {
    BeginofAmount:number,
         ItemCount : number,
         ItemType : any,
         EndofAmount : number,
         ChangeFundID : number,
         Date : Date ,
         StartDate :  Date ,
         EndDate :  Date,
         RevenueAmount :number,
         ReceivedBalance : number,
         FloatAmount :  number,
         FloatTotalAmount :  number,
         ReceivedTotalAmount :  number,
         FloatDenomination : any,
         ReceivedDenomination : any,
         ICNCashId :  number,
         Hundreds :  number,
         Fifties :  number,
         Twenties :  number,
         Tens :  number,
         Fives :  number,
         Twos :  number,
         Ones :  number,
         Halfs :  number,
         Quarters :  number,
         Dimes :  number,
         Nickles :  number,
         Pennies :  number,
         Type :  number,
         FundDate :  Date,
         CRDRFlag :  any,
         ICNId :  number,
         ICNStatus :  any ,
         UserId :  number,
         UserName :  any,
         CreatedUser :  any,
         CreatedDate :Date ,
         UpdatedDate :  Date ,
         UpdatedUser :  any,
         RoleId :  number,
         RoleName :  any,
         SortColumn :  any,
         SortDir :  number,
         PageNumber :  number,
         PageSize :  number,
         ReCount :  number
}