export interface IItemtDetailsResponse{
    InventoryId: number,
    VendorID:number,
    ItemCode: string,
    FacilityCode: string,
    HexTagId: string,
    SerialNumber: string,
    CustomerId: number,
    LocationId: number,
    ShipmentId: number,
    BatchId: number,
    ManufactureDate: Date,
    WarrantyStartDate: Date,
    WarrantyEndDate: Date,
    InventoryStatusDate: Date,
    RMANumber: string,
    ItemType: string,
    ItemStatus: string,
    ItemId: number,
    CreatedDate: Date,
    CreatedUser: string,
    UpdatedDate: Date,
    UpdatedUser: string,
    RecordCount: number,
    OrderNumber:any,
    OrderDate:Date,
    ShipmentStatus:any,
    WarrantyName:string,
    WarrantyInMonths:number,
    ContractNumber:any
   
}