import { IInventoryItemRequest } from './inventoryitemsrequest';
import { IItemBatchRequest } from './itembatchrequest';
export interface IShipmentDetailsrequest {
    ReceivedDate: any,
    PurchaseOrderID: number,
    VendorID: number,
    ShipLabel: string,
    OrderDate: Date,
    ShipDate: any,
    BatchCount: number,
    ProductNumber: number,
    Note: string,
    ShipmentStatus: string,
    ReceivedEmployeeId: number,
    CreatedUser: string,
    PartNumber: number,
    PartDescription: string,
    WarrantyStartDate: Date,
    WarrantyEndDate: Date,
    PackingListNumber: number,
    TagSupplierId: number,
    Mounting: string,
    ItemID: number,
    ItemCode: string,
    InventoryItem: IInventoryItemRequest,
    ItemInventoryBatchDetails: IItemBatchRequest,
    UserId: number,
    LoginId: number,
    User: string,
    ActivitySource: string,
    ItemQuantity: number,
    PurchaseOrderStatus: string,
    Protocol: string,
    addressType: string,
    CompanyName: string,
    ContractNumber: string,
    ItemTypeDescription: string,
    ItemName: string,
    DescLength: number,
    purchaseOrderName: any

}