
export interface ITagsDistributionRequest {
    SerialNumber: string,
    Mounting: string,
    Protocol: string,
    ReqCount: number,
    LocationName: string,
    UserName: string,
    TagReqDate: string,
    IsPaging: number,
    CreatedUser:string,
    UserId:number,
    LoginId:number,
    ActivitySource:string,
    TagReqComment:string,
    StartDate:string,
    EndDate:string,
    SortColumn: string,
    SortDirection: boolean,
    PageNumber: number,
    PageSize: number,
    TagReqId:number,
    Subsystem:string,
    ReCount:number,
    LocationId:number,
}