export interface IAlertsAndCommunicationsRequest {
    AlertType: string,
    AlertTypeDesc: string,
    AlertText: string,
    AlertDate: Date,
    AlertStatus: string,
    LoggedUserID: number,
    SMSFlag: number,
    EMAILFLAG: number,
    MAILFlag: number,
    NONEFLAG: number,
    AlertTypeId: number,
    BITMAPVALUE: number,
    CustomerId: number,
    SMSBITMAPVALUE: number,
    EMAILBITMAPVALUE: number,
    MAILBITMAPVALUE: number,
    NONEBITMAPVALUE: number,
    UpdatedUser: string,
    SubSystem: string,
    ActivityType: string,
    SMSNoteText: string,
    EMAILNoteText: string,
    MAILNoteText: string,
    ActivitySource: string,
    LinkSourceName: string,

}