import { IPaging } from "../../../shared/models/paging";
export interface IWorkFlowStages {
    LoginId: number,
    UserId: number,
    StageId: number,
    StageName: string,
    StageOrder: number,
    StepsCount: number,
    StageIsActive: boolean,
    WorkFlowStageName: string,
    WorkFlowStageOrder: string,
    StageStepId: number,
    StepDesc: string,
    StepOrder: number,
    AgingPeriodDays: number,
    StageStepIsActive: boolean,
    StageStepFeeId: number,
    FeeTypeId: number,
    FeeAlias: string,
    Amount: number,
    StageStepFeeIsActive: boolean,
    PerformedBy: string,
    ActivitySource: string,
    FeaturesCode: string,
    Paging: IPaging,
    ViewStatus: string,
    StageStepCode: string,
    GracePeriodDays: number,
    ThresholdAmount: number,
    AppliedFor: string,
    FeeCode: string
}