export interface IItemResponse {
    ItemId: number,
    ItemCode: string,
    ItemName: string,
    ItemDesc: string,
    ItemTypeId: number,
    ThresholdCount: number,
    ItemTypeName: string,
    ItemPrice: string,
    CompanyName: string,
    VendorId: string,
    ItemTypedDesc: string,
    TotalCount: number,
    ItemQuantity: number,
    MinOrderLevel: number,
    MaxOrderLevel: number,
    RecCount: number,
    OrderNumber: string,
    OrderDate: string,
    Protocol: string,
    Mounting: string,
    TagDeposit: string,
    TagStatus: any;
}