import { IAddressRequest } from './../../../payment/models/addressrequest';
export interface ITagRequest {
    SerialNumber: string,
    TagStatus: string,
    PreviousTagStatus: string,
    TagType: string,
    TagName: string,
    FacilityCode: string,
    TagLocation: string,
    ManufactureDate: Date,
    HexTagNumber: string,
    StartEffectiveDate
    StatusDate: Date,
    EndEffectiveDate
    TagAlias: string,
    UserName: string,
    TagReqType: string,
    CustTagReqId: number,
    ReqCount: number,
    TagPurchaseMethod: string,
    TagDeliveryMethod: string,
    TagReqComment: string,
    TagReqDate: Date,
    CustomerId: number,
    AccountId: number,
    TagTobeReplaced: string,
    IsReplacedTagReturned
    VehicleId: number,
    VehicleClassId: number,
    FulfilledQty: number,
    SubSystem: string,
    ActivityType: string,
    ActivitySource: string,
    AdjustmentReason: string,
    ShipmentId: number,
    PurchaseOrderNumber: string,
    WarrantyEndDate:Date
    ICNId: number,
    LoginId: number,
    UserId: number,
    TagSearchActivityInd: string,
    PreviousDate: Date,
    IsPageLoad: boolean,
    IsSearch: boolean,
    RMANumber: string,
    AssignedOrReturnedType: string,
    ItemCode: string,
    TagDeliveryOption: string,
    ShipmentAddress: IAddressRequest[],
    TotalRequiredAmount: string,
    IsNotification: boolean,
    PreviousTagAlias: string,
    Mounting: string,
    Protocol: string,
    TagPurchaseMethodCode: string,
    SplitCustomerId: number,
    RevenueCategory: string,
    ItemId: number,
    PageNumber: number,
    PageSize: number,
    SortColumn: string,
    SortDirection: boolean,
    internalUserId: number,
    vehicleNumber: string,
    tagId: string,
    accountId: string,
    timePeriod:any;

}