import { ISystemActivities } from "../../../shared/models/systemactivitiesrequest";
export interface IBusinessesProcessesRequest {
    SystemActivities: ISystemActivities,
    BusinessProcessID: number,
    SortColumn: string,
    SortDir: number,
    PageNumber: number,
    PageSize: number,
    ReCount: number,
    IsPaging: boolean,
    user: string,
    BusinessProcessCode: string,
    BusinessProcessDesc: string,
    IsAvailable: boolean,
    Status: string,
    TxnTypeAssociations: any,
    TxnCode: string,
    User: string,
    ChartOfAccountIDs: any,
    ChartAccountDesc: string,
    ChartOfAccountNames: string,
    LineItemCode: string,
    intTxnTypeId: number,
    UserId: number,
    LoginId: number,
    IsSearch: string,
}